name: Muchsync with notmuch mailing list archive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  notmuch-ml:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y notmuch libnotmuch-dev wget build-essential ssh curl autoconf automake pkg-config libtool libsqlite3-dev libxapian-dev sqlite3
    - run: echo -e "[database]\npath=/tmp/notmuch-list\n\n[user]\nname=test\nprimary_email=test@test.com\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted;\nauthors_separator=;\nauthors_matched_separator=;\n\n[maildir]\nsynchronize_flags=true\n\n[crypto]\ngpg_path=gpg" > ~/.notmuch-config
    - run: wget https://nmbug.notmuchmail.org/archive/notmuch-list.tar.xz && tar xf notmuch-list.tar.xz 2018-02
      working-directory: /tmp
    - run: notmuch new
    - run: notmuch tag -unread date:..1M
    - run: notmuch tag +patch subject:patch or attachment:.patch
    - run: notmuch tag +bug subject:bug or body:bug
    - run: notmuch tag +question body:question or subject:'?'
    - run: notmuch tag +todo date:1M.. and tag:patch

    - run: ./autogen.sh && ./configure && make
      working-directory: .

    - run: mkdir /tmp/muchsync-test
    - run: mkdir ~/.ssh
    - run: chmod 700 ~/.ssh
    - run: ssh-keygen -N "" -f ~/.ssh/test
    - run: cp ~/.ssh/test.pub ~/.ssh/authorized_keys
    - run: chmod 600 ~/.ssh/authorized_keys
    - run: sudo service ssh start

    - run: $GITHUB_WORKSPACE/muchsync -C /tmp/muchsync-test/.notmuch-config -s "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no" -vvv -r $GITHUB_WORKSPACE/muchsync --init /tmp/muchsync-test localhost
    - run: notmuch count '*' > /tmp/server.count
    - run: notmuch count '*' > /tmp/client.count
      env:
        NOTMUCH_CONFIG: /tmp/muchsync-test/.notmuch-config
    - run: if [ `cat /tmp/server.count` -neq `cat /tmp/client.count` ]; then exit 1; fi
    - run: diff -rq /tmp/notmuch-list /tmp/muchsync-test || exit 0
    
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM configuration"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM configuration"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM sync_vector"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM sync_vector"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM xapian_dirs"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM xapian_dirs"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM message_ids"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM message_ids"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM xapian_files"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM xapian_files"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM maildir_hashes"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM maildir_hashes"
    - run: sqlite /tmp/notmuch-list/.notmuch/muchsync/state.db "SELECT * FROM xapian_nlinks"
    - run: sqlite /tmp/muchsync-test/.notmuch/muchsync/state.db "SELECT * FROM xapian_nlinks"

    - run: if [ `notmuch search --output=tags id:87r05rqsbz.fsf@tethera.net | tr -d '\n'` != "question" ]; then exit 1; fi
    - run: notmuch tag +foo id:87r05rqsbz.fsf@tethera.net
    - run: if [ `notmuch search --output=tags id:87r05rqsbz.fsf@tethera.net | tr -d '\n'` != "fooquestion" ]; then exit 1; fi
    - run: if [ `notmuch search --output=tags id:87r05rqsbz.fsf@tethera.net | tr -d '\n'` != "question" ]; then exit 1; fi
      env:
        NOTMUCH_CONFIG: /tmp/muchsync-test/.notmuch-config
    - run: $GITHUB_WORKSPACE/muchsync -C /tmp/muchsync-test/.notmuch-config -s "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no" -vvv -r $GITHUB_WORKSPACE/muchsync localhost
    - run: diff -rq /tmp/notmuch-list /tmp/muchsync-test || exit 0
    - run: if [ `notmuch search --output=tags id:87r05rqsbz.fsf@tethera.net | tr -d '\n'` != "fooquestion" ]; then exit 1; fi
      env:
        NOTMUCH_CONFIG: /tmp/muchsync-test/.notmuch-config
